services:
  - type: web
    name: nja-platform
    env: python
    rootDir: /
    buildCommand: ./build.sh
    startCommand: bash start.sh
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        sync: false
    database:
      name: nja-platform-db
      plan: free
